server:
  port: 8085

app:
  type-run: DEV

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"

      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework: ERROR
    reactor.netty: ERROR
    br.com.mesko: INFO

jwt:
  secret: 1234567890123456789012345678901234567890
  expiration: 3600000